type Post {
  id: ID!
  title: String!
  content: String!
  category: Category!
  author: User!
}

input PostInput {
  title: String!
  content: String!
  category: ID!
  author: ID!
}

type Query {
  posts: [Post!]!
  post(id: ID!): Post!
}

type Mutation {
  createPost(data: PostInput!): Post!
  updatePost(id: ID!, data: PostInput!): Post!
  deletePost(id: ID!): Boolean
}
