type Category {
  id: ID!
  cat_id: Int!
  name: String!
}

input CategoryInput {
  cat_id: Int!
  name: String!
}

type Query {
  categories: [Category!]!
  category(id: ID!): Category!
}

type Mutation {
  createCategory(data: CategoryInput!): Category!
  updateCategory(id: ID!, data: CategoryInput!): Category!
  deleteCategory(id: ID!): Boolean
}
